export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE"; 

export const UPDATE_COMMENT_REQUEST = "UPDATE_COMMENT_REQUEST";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAILURE = "UPDATE_COMMENT_FAILURE"; 

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE"; 
   
export const FIND_COMMENT_BY_POST_ID_REQUEST = "FIND_COMMENT_BY_POST_ID_REQUEST";
export const FIND_COMMENT_BY_POST_ID_SUCCESS = "FIND_COMMENT_BY_POST_ID_SUCCESS";
export const FIND_COMMENT_BY_POST_ID_FAILURE = "FIND_COMMENT_BY_POST_ID_FAILURE";

